version: '3.3'
services:
  mspedido:
    image: calcabrine/mspedido:1.0
    container_name: mspedido
    ports:
      - "7000:80"
    environment:
      - MS_PEDIDOS_CONNSTRING=${MS_PEDIDOS_CONNSTRING}
      - MS_RABBITMQ_HOST=${MS_RABBITMQ_HOST}
      - MS_RABBITMQ_PORT=${MS_RABBITMQ_PORT}
      - MS_RABBITMQ_USER=${MS_RABBITMQ_USER}
      - MS_RABBITMQ_PASSWORD=${MS_RABBITMQ_PASSWORD}
      - MS_RABBITMQ_VHOST=${MS_RABBITMQ_VHOST}
    restart: unless-stopped