name: DeployMicroservicos

on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
          default_bump: minor
          release_branches: main

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image mscadastro
        uses: docker/build-push-action@v4
        with:
          context: ./MS.Cadastro
          push: true
          tags: 
            edileal/mscadastro:${{steps.tag_version.outputs.new_tag}}
            edileal/mscadastro:latest
          

      - name: Build and push Docker image msemail
        uses: docker/build-push-action@v4
        with:
            context: ./MS.Emails
            push: true
            tags: 
              edileal/msemail:${{steps.tag_version.outputs.new_tag}}
              edileal/msemail:latest

      - name: Docker-Compose Remote Deployment MS.Cadastro
        uses: alex-ac/github-action-ssh-docker-compose@master
        with:
          ssh_host: ${{ secrets.DEPLOY_SERVER_SSH_HOST }}
          ssh_private_key: ${{ secrets.DEPLOY_SERVER_SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.DEPLOY_SERVER_SSH_USER }}
          docker_compose_prefix: mscadastro
          docker_compose_file: mscadastro-compose.yml
          docker_compose_down: 'true'


